# Generated by Django 5.2.5 on 2025-08-18 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('account', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_trans_id', models.BigIntegerField(blank=True, null=True)),
                ('status_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'atmos_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
