# Generated by Django 5.2.5 on 2025-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmostransaction',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='atmostransaction',
            name='store_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atmostransaction',
            name='terminal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atmostransaction',
            name='webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atmostransaction',
            name='account',
            field=models.CharField(help_text='Order ID or account identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='atmostransaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
