# Generated by Django 5.2.5 on 2025-08-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atmos', '0002_atmostransaction_payment_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmostransaction',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='atmostransaction',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='atmostransaction',
            name='store_id',
        ),
        migrations.RemoveField(
            model_name='atmostransaction',
            name='success_trans_id',
        ),
        migrations.RemoveField(
            model_name='atmostransaction',
            name='terminal_id',
        ),
        migrations.RemoveField(
            model_name='atmostransaction',
            name='webhook_received_at',
        ),
    ]
